# Generated by Django 2.2.7 on 2019-11-26 23:30

import catalog.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.CharField(max_length=1000)),
                ('genres', djongo.models.fields.ArrayModelField(model_container=catalog.models.Genre)),
                ('runtime', models.PositiveIntegerField()),
                ('cast', djongo.models.fields.ArrayModelField(model_container=catalog.models.Cast)),
                ('poster', models.CharField(max_length=1000, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('fullplot', models.CharField(max_length=1000)),
                ('countries', djongo.models.fields.ArrayModelField(model_container=catalog.models.Country)),
                ('released', models.DateField()),
                ('languages', djongo.models.fields.ArrayModelField(model_container=catalog.models.Language)),
                ('directors', djongo.models.fields.ArrayModelField(model_container=catalog.models.Director)),
                ('writers', djongo.models.fields.ArrayModelField(model_container=catalog.models.Writers)),
                ('year', models.PositiveIntegerField()),
                ('imdb', djongo.models.fields.EmbeddedModelField(model_container=catalog.models.Imdb, null=True)),
                ('tomatoes', djongo.models.fields.EmbeddedModelField(model_container=catalog.models.Tomatoes, null=True)),
                ('Douban', djongo.models.fields.EmbeddedModelField(model_container=catalog.models.DouBan, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('movie_id', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Movies')),
                ('user_id', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Users')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
